import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import { Footer } from "@/components/footer";
import "./globals.css";

const bricolage_grotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${bricolage_grotesque.variable} antialiased min-h-screen flex flex-col`}
      >
        <div className="flex-1">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
